# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define the orb that would be used
orbs: 
  awscli: circleci/aws-cli@2.0.3

# Define the jobs
jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
# Invoke jobs via workflows

workflows:
  my-workflow:
    jobs:
      - create_infrastructure
